<?php
/**
 * @file
 * Code for the Ding library opening hours related blocks.
 */

/**
 * Implements hook_block_info().
 */
function ding_library_opening_hours_block_info() {
  return array(
    'ding_library_opening_hours' => array(
      'info' => t('Opening hours for this week'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'ding_library_opened_today' => array(
      'info' => t('Todays opening hours for all libraries'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function ding_library_opening_hours_block_view($delta = '') {
  $block = array();

  if ($delta == 'ding_library_opening_hours' && $node = menu_get_object()) {
    drupal_add_css(drupal_get_path('module', 'ding_library_opening_hours') . '/css/ding_library_opening_hours.css', array('type' => 'file'));
    $block['subject'] = t('Hours');
    $block['content'] = array(
      '#theme' => 'ding_library_opening_hours_view',
      '#node' => $node,
    );
  }

  if ($delta == 'ding_library_opened_today') {
    drupal_add_css(drupal_get_path('module', 'ding_library_opening_hours') . '/css/ding_library_opening_hours.css', array('type' => 'file'));
    $block['subject'] = t('Opened today');
    $block['content'] = array(
      '#theme' => 'ding_library_opened_today_view',
    );
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function ding_library_opening_hours_theme($existing, $type, $theme, $path) {
  return array(
    'ding_library_opening_hours_view' => array(
      'path' => $path . '/templates',
      'template' => 'ding_library_opening_hours_view',
      'variables' => array('node' => NULL),
    ),
    'ding_library_opened_today_view' => array(
      'path' => $path . '/templates',
      'template' => 'ding_library_opened_today_view',
      'variables' => array('libraries' => NULL),
    ),
  );
}

/**
 * Preprocess variables for our template.
 */
function template_preprocess_ding_library_opening_hours_view(&$vars) {
  $node = $vars['node'];
  // Some minor date manipulations to get the correct range for the block
  $full_day            = 24 * 60 * 60;
  $current_date        = time();
  $current_day_of_week = date('w');
  $start_of_week       = $current_date - ($full_day * $current_day_of_week) + 1;
  $start_date          = date('Y-m-d', $start_of_week);

  // Generate dummy holder for the current week
  $days = array();
  for ($i = 0; $i < 7; $i++) {
    $start_of_week  += $full_day;
    $day_date        = date('Y-m-d', $start_of_week);
    $days[$day_date] = array(
      'day_name' => date('l', $start_of_week),
    );
  }

  $end_date = date('Y-m-d', $start_of_week);

  // Load the opening hours from DB for theming
  $opening_hours = opening_hours_instance_load_multiple($node->nid, $start_date, $end_date);
  foreach ($opening_hours as $instance) {
    if (isset($days[$instance->date]['day_name'])) {
      $days[$instance->date]['end_time'] = $instance->end_time;
      $days[$instance->date]['start_time'] = $instance->start_time;
    }
  }

  $vars['days'] = $days;
}

/**
 * Preprocess variables for our template.
 */
function template_preprocess_ding_library_opened_today_view(&$vars) {
  $libraries = array();
  $today = date('Y-m-d');

  // Load all libraries form list, because there are less libraries than dates
  // and because of how opening_hours_instance_load_multiple works
  $raw_libraries = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('n.type', 'ding_library')
    ->condition('n.status', NODE_PUBLISHED)
    ->execute()
    ->fetchAll();

  if (count($raw_libraries)) {
    foreach ($raw_libraries as $library) {
      $libraries[$library->nid]['title'] = l($library->title, 'node/' . $library->nid);
    }

    // Get all dates for today
    $opening_hours = opening_hours_instance_load_multiple(array_keys($libraries), $today, $today);
    foreach ($opening_hours as $hour) {
      $libraries[$hour->nid]['start_time'] = $hour->start_time;
      $libraries[$hour->nid]['end_time'] = $hour->end_time;
    }
  }

  $vars['libraries'] = $libraries;
}

