<?php
/**
 * @file
 * Code for the Ding library opening hours related blocks.
 */

include_once 'ding_library_opening_hours.features.inc';

/**
 * Implements hook_menu().
 */
function ding_library_opening_hours_menu() {
  $items = array();
  $items['ding_library/opening_hours/save'] = array(
    'page callback' => 'ding_library_opening_hours_save',
    'access callback' => 'user_access',
    'access arguments' => array('edit opening hours for content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function ding_library_opening_hours_block_info() {
  return array(
    'ding_library_opening_hours' => array(
      'info' => t('Ding: Opening hours for this week'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'ding_library_opened_today' => array(
      'info' => t("Ding: Today's opening hours for all libraries"),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function ding_library_opening_hours_block_view($delta = '') {
  $block = array();

  if ($delta == 'ding_library_opening_hours' && $node = menu_get_object()) {
    drupal_add_css(drupal_get_path('module', 'ding_library_opening_hours') . '/css/ding_library_opening_hours.css', array('type' => 'file'));
    $block['subject'] = t('Hours');
    $block['content'] = array(
      '#theme' => 'ding_library_opening_hours_view',
      '#node' => $node,
    );
  }

  if ($delta == 'ding_library_opened_today') {
    drupal_add_css(drupal_get_path('module', 'ding_library_opening_hours') . '/css/ding_library_opening_hours.css', array('type' => 'file'));
    drupal_add_js(drupal_get_path('module', 'ding_library_opening_hours') . '/js/ding_library_opening_hours.js', array('type' => 'file'));

    $block['subject'] = t('Today\'s opening hours');
    $block['content'] = array(
      '#theme' => 'ding_library_opened_today_view',
    );
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function ding_library_opening_hours_theme($existing, $type, $theme, $path) {
  return array(
    'ding_library_opening_hours_view' => array(
      'path' => $path . '/templates',
      'template' => 'ding_library_opening_hours_view',
      'variables' => array('node' => NULL),
    ),
    'ding_library_opened_today_view' => array(
      'path' => $path . '/templates',
      'template' => 'ding_library_opened_today_view',
      'variables' => array('libraries' => NULL),
    ),
  );
}

/**
 * Preprocess variables for our template.
 */
function template_preprocess_ding_library_opening_hours_view(&$vars) {
  $node = $vars['node'];
  // Some minor date manipulations to get the correct range for the block
  $full_day            = 24 * 60 * 60;
  $current_date        = time();
  $current_day_of_week = date('w');
  $start_of_week       = $current_date - ($full_day * $current_day_of_week) + 1;
  $start_date          = date('Y-m-d', $start_of_week);

  // Generate dummy holder for the current week
  $days = array();
  for ($i = 0; $i < 7; $i++) {
    $start_of_week  += $full_day;
    $day_date        = date('Y-m-d', $start_of_week);
    $days[$day_date] = array(
      'day_name' => date('l', $start_of_week),
    );
  }

  $end_date = date('Y-m-d', $start_of_week);

  // Load the opening hours from DB for theming
  $opening_hours = opening_hours_instance_load_multiple($node->nid, $start_date, $end_date);
  foreach ($opening_hours as $instance) {
    if (isset($days[$instance->date]['day_name'])) {
      $days[$instance->date]['end_time'] = $instance->end_time;
      $days[$instance->date]['start_time'] = $instance->start_time;
    }
  }

  $vars['days'] = $days;
}

/**
 * Preprocess variables for our template.
 */
function template_preprocess_ding_library_opened_today_view(&$vars) {
  $libraries = array();
  $today = date('Y-m-d');
  global $language;

  $qid = _ding_library_opening_hours_nodequeue_id();

  // Load all libraries form list, because there are less libraries than dates
  // and because of how opening_hours_instance_load_multiple works
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('n.type', 'ding_library')
    ->condition('n.status', NODE_PUBLISHED)
    ->condition('n.language', array($language->language, 'und'), 'IN');

  $query->join('nodequeue_nodes', 'nq', 'n.nid = nq.nid AND nq.qid = ' . $qid);
  $query->orderBy("nq.position", "ASC");

  $raw_libraries = $query->execute()->fetchAll();

  if (count($raw_libraries)) {
    foreach ($raw_libraries as $library) {
      $libraries[$library->nid]['title'] = l($library->title, 'node/' . $library->nid);
    }

    // Get all dates for today
    $opening_hours = opening_hours_instance_load_multiple(array_keys($libraries), $today, $today);
    foreach ($opening_hours as $hour) {
      $libraries[$hour->nid]['hours'][$hour->instance_id]['start_time'] = $hour->start_time;
      $libraries[$hour->nid]['hours'][$hour->instance_id]['end_time'] = $hour->end_time;
      $libraries[$hour->nid]['hours'][$hour->instance_id]['notice'] = $hour->notice;
    }
  }

  $vars['libraries'] = $libraries;
}

/**
 * Implement hook_preprocess_page().
 *
 * @param array $variables
 *   Available variables on page.
 */
function ding_library_opening_hours_preprocess_page(&$variables) {
  $args = arg();
  if ($args && $args[0] == 'node' && !empty($args[2]) && $args[2] == 'opening_hours') {
    $js_path = drupal_get_path('module', 'ding_library_opening_hours') . '/js/ding_library_opening_hours.views.js';
    drupal_add_js($js_path, array(
      'type' => 'file',
      'scope' => 'footer',
      'group' => JS_THEME,
      'weight' => 99,
    ));
  }
}

/**
 * Update node queue on opening hours schedule save.
 */
function ding_library_opening_hours_save() {
  if (!empty($_POST['nid']) && (int) $_POST['nid']) {
    $nid = $_POST['nid'];

    $qid = _ding_library_opening_hours_nodequeue_id();
    $queue = nodequeue_load($qid);

    _ding_library_opening_hours_update_queue($queue, $nid);
  }
}

/**
 * Get nodequeue id based on machine name.
 *
 * @return int
 *   Nodequeue id.
 */
function _ding_library_opening_hours_nodequeue_id() {
  // Get node queue.
  $query = db_select('nodequeue_queue', 'nq')
    ->fields('nq', array('qid'))
    ->condition('nq.name', 'opening_hours');
  $query->join('nodequeue_subqueue', 'nsq', 'nsq.qid = nq.qid');
  $result = $query->execute()->fetchObject();
  $qid = $result->qid;

  return $qid;
}

/**
 * Update queue based on the modifications made on the library node.
 *
 * @param \stdClass $queue
 *   Nodequeue object.
 * @param int $nid
 *   Node id.
 */
function _ding_library_opening_hours_update_queue($queue, $nid) {
  $subqueues = nodequeue_load_subqueues_by_queue($queue->qid);

  foreach ($subqueues as $subqueue) {
    $position = nodequeue_get_subqueue_position($subqueue->sqid, $nid);
    if (!$position) {
      nodequeue_subqueue_add($queue, $subqueue, $nid);
    }
    else {
      nodequeue_queue_front($subqueue, $position);
    }
  }
}

/**
 * Implements hook_node_update().
 */
function ding_library_opening_hours_node_update($node) {
  // Add saved node to queue.
  if ($node->type == 'ding_library') {
    $qid = _ding_library_opening_hours_nodequeue_id();
    $queue = nodequeue_load($qid);

    _ding_library_opening_hours_update_queue($queue, $node->nid);
  }
}
